(() => {
  "use strict";
  const $ = id => document.getElementById(id);
  const esc = value => String(value).replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const pretty = value => typeof value === "string" ? value : JSON.stringify(value, null, 2);
  const copy = async text => { await navigator.clipboard.writeText(text); };
  const download = (name, text, type="text/plain") => { const a=document.createElement("a"); a.href=URL.createObjectURL(new Blob([text],{type})); a.download=name; a.click(); URL.revokeObjectURL(a.href); };
  const panel = (input, output, note="") => `<div class="advanced-grid"><section class="advanced-panel"><h2>入力</h2>${input}</section><section class="advanced-panel"><h2>結果</h2>${output}</section></div>${note ? `<p class="advanced-note">${note}</p>`:""}`;
  const buttons = labels => `<div class="advanced-actions">${labels.map(([id,label,secondary])=>`<button id="${id}" type="button" class="${secondary?"secondary":"primary"}-button">${label}</button>`).join("")}</div>`;
  const renderText = text => { $("result").textContent=text; };

  function sanitizeHar(value) {
    const sensitive=/authorization|cookie|set-cookie|token|secret|api[-_]?key|password/i;
    let removed=0;
    const walk=(v,key="")=>{
      if (Array.isArray(v)) return v.map(x=>walk(x,key));
      if (v && typeof v==="object") { const out={}; for(const [k,x] of Object.entries(v)){ if(sensitive.test(k)){out[k]="[REDACTED]";removed++;} else if(k==="headers"&&Array.isArray(x)){out[k]=x.map(h=>sensitive.test(h.name||"")?(removed++,{...h,value:"[REDACTED]"}):walk(h));} else if(k==="cookies"&&Array.isArray(x)){out[k]=x.map(c=>(removed++,{...c,value:"[REDACTED]"}));} else if(k==="queryString"&&Array.isArray(x)){out[k]=x.map(q=>sensitive.test(q.name||"")?(removed++,{...q,value:"[REDACTED]"}):walk(q));} else if(k==="url"&&typeof x==="string"){try{const u=new URL(x);for(const name of [...u.searchParams.keys()])if(sensitive.test(name)){u.searchParams.set(name,"[REDACTED]");removed++;}out[k]=u.toString();}catch(e){out[k]=x;}} else out[k]=walk(x,k); } return out; }
      return sensitive.test(key)&&v ? (removed++,"[REDACTED]") : v;
    };
    return {data:walk(value),removed};
  }
  function dataMagic(raw){
    const out=[]; const s=raw.trim();
    try { out.push(["JSON",JSON.stringify(JSON.parse(s),null,2)]); } catch(e){}
    if(/^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\./.test(s)){try{out.push(["JWTペイロード",decodeURIComponent(escape(atob(s.split(".")[1].replace(/-/g,"+").replace(/_/g,"/"))))]);}catch(e){}}
    if(/^[A-Za-z0-9+/=\s]+$/.test(s)&&s.length%4===0){try{const v=decodeURIComponent(escape(atob(s.replace(/\s/g,"")))); if(v)out.push(["Base64デコード",v]);}catch(e){}}
    if(/%[0-9a-f]{2}/i.test(s)){try{out.push(["URLデコード",decodeURIComponent(s)]);}catch(e){}}
    if(/^(?:[0-9a-f]{2}\s*)+$/i.test(s)){try{out.push(["16進数→文字",(s.match(/[0-9a-f]{2}/gi)||[]).map(x=>String.fromCharCode(parseInt(x,16))).join("")]);}catch(e){}}
    if(/^\d{10,13}$/.test(s)){const n=Number(s)*(s.length===10?1000:1); const d=new Date(n); if(!isNaN(d))out.push(["Unix時刻",d.toLocaleString("ja-JP")]);}
    out.push(["URLエンコード",encodeURIComponent(raw)]);
    return out;
  }
  function parseCurl(raw){
    const tokens=raw.match(/(?:[^\s"']+|"[^"]*"|'[^']*')+/g)||[]; const clean=x=>(x||"").replace(/^['"]|['"]$/g,"");
    let method="GET",url="",body=""; const headers={};
    for(let i=0;i<tokens.length;i++){const t=tokens[i]; if(t==="-X"||t==="--request")method=clean(tokens[++i]).toUpperCase(); else if(t==="-H"||t==="--header"){const h=clean(tokens[++i]);const p=h.indexOf(":");if(p>0)headers[h.slice(0,p).trim()]=h.slice(p+1).trim();} else if(["-d","--data","--data-raw"].includes(t)){body=clean(tokens[++i]);if(method==="GET")method="POST";} else if(/^https?:\/\//.test(clean(t)))url=clean(t);}
    if(!url)throw Error("URLを確認できませんでした"); return {method,url,headers,body};
  }
  function curlOutputs(r){const hs=JSON.stringify(r.headers,null,2);const opt=`{ method: ${JSON.stringify(r.method)}, headers: ${hs}${r.body?`, body: ${JSON.stringify(r.body)}`:""} }`;return {Fetch:`fetch(${JSON.stringify(r.url)}, ${opt});`,Axios:`axios({ url: ${JSON.stringify(r.url)}, method: ${JSON.stringify(r.method.toLowerCase())}, headers: ${hs}${r.body?`, data: ${JSON.stringify(r.body)}`:""} });`,Python:`requests.request(${JSON.stringify(r.method)}, ${JSON.stringify(r.url)}, headers=${JSON.stringify(r.headers)}${r.body?`, data=${JSON.stringify(r.body)}`:""})`,PowerShell:`Invoke-RestMethod -Method ${r.method} -Uri ${JSON.stringify(r.url)}${Object.keys(r.headers).length?` -Headers ${JSON.stringify(r.headers)}`:""}${r.body?` -Body ${JSON.stringify(r.body)}`:""}`};}
  function apiDiff(oldVal,newVal,path="$",out=[]){
    const type=v=>Array.isArray(v)?"array":v===null?"null":typeof v; const a=type(oldVal),b=type(newVal);
    if(a!==b){out.push({level:"danger",text:`${path}: 型が ${a} から ${b} に変更`});return out;}
    if(a==="object"){for(const k of Object.keys(oldVal)){if(!(k in newVal))out.push({level:"danger",text:`${path}.${k}: 削除されました`});else apiDiff(oldVal[k],newVal[k],`${path}.${k}`,out);}for(const k of Object.keys(newVal)){if(!(k in oldVal))out.push({level:"info",text:`${path}.${k}: 追加されました`});}}
    if(a==="array"&&oldVal.length&&newVal.length)apiDiff(oldVal[0],newVal[0],`${path}[]`,out); return out;
  }
  function regexAudit(pattern){const warnings=[];if(/\([^)]*[+*][^)]*\)[+*{]/.test(pattern))warnings.push("量指定子の入れ子があり、ReDoSの危険があります");if(/\.[+*].*\.[+*]/.test(pattern))warnings.push("広いワイルドカードが複数あり、バックトラックが増える可能性があります");if(/\([^)]*\|[^)]*\)[+*]/.test(pattern))warnings.push("繰り返し内の選択肢が曖昧な可能性があります");return warnings;}
  function cspAudit(text){const warnings=[];if(/unsafe-inline/.test(text))warnings.push("unsafe-inline はインラインコードの実行を許します");if(/unsafe-eval/.test(text))warnings.push("unsafe-eval は文字列からのコード実行を許します");if(/(?:^|\s)\*(?:\s|;|$)/.test(text))warnings.push("ワイルドカード * は許可範囲が広すぎます");if(/data:/.test(text))warnings.push("data: の許可範囲を必要最小限にしてください");return warnings;}
  function cronValues(field,min,max){const set=new Set();for(const part of field.split(",")){let base=part,step=1;if(part.includes("/")){[base,step]=part.split("/");step=Number(step);}let start=min,end=max;if(base!=="*"){if(base.includes("-"))[start,end]=base.split("-").map(Number);else start=end=Number(base);}if(!step||start<min||end>max)throw Error("Cronの値が範囲外です");for(let i=start;i<=end;i+=step)set.add(i);}return set;}
  function nextCron(expr,count=20){const f=expr.trim().split(/\s+/);if(f.length!==5)throw Error("5項目形式（分 時 日 月 曜日）で入力してください");const sets=[cronValues(f[0],0,59),cronValues(f[1],0,23),cronValues(f[2],1,31),cronValues(f[3],1,12),cronValues(f[4],0,6)];const out=[],d=new Date();d.setSeconds(0,0);d.setMinutes(d.getMinutes()+1);for(let i=0;i<525600*2&&out.length<count;i++,d.setMinutes(d.getMinutes()+1)){if(sets[0].has(d.getMinutes())&&sets[1].has(d.getHours())&&sets[2].has(d.getDate())&&sets[3].has(d.getMonth()+1)&&sets[4].has(d.getDay()))out.push(new Date(d));}return out;}
  function actionsAudit(yaml){const rules=[[/permissions:\s*write-all/i,"danger","permissions: write-all は権限が広すぎます"],[/pull_request_target\s*:/i,"danger","pull_request_target は未信頼コードの実行に注意が必要です"],[/uses:\s*[^\s]+@(main|master|v\d+)\b/i,"warn","ActionをコミットSHAで固定していません"],[/(curl|wget)[^\n|]*\|\s*(sh|bash)/i,"danger","ダウンロードしたスクリプトを直接実行しています"],[/echo[^\n]*\$\{\{\s*secrets\./i,"danger","secretをログへ出力する可能性があります"],[/^\s*sudo\s+/mi,"warn","sudoコマンドの必要性を確認してください"]];const out=rules.filter(r=>r[0].test(yaml)).map(r=>({level:r[1],text:r[2]}));if(!/^permissions\s*:/mi.test(yaml))out.push({level:"warn",text:"ワークフロー全体のpermissionsが明示されていません"});return out;}
  function redact(text){return text.replace(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/g,"[EMAIL]").replace(/(authorization|token|password|secret|api[_-]?key)(\s*[:=]\s*)([^\s,}\]]+)/ig,"$1$2[REDACTED]").replace(/(?:[A-Za-z]:\\|\/Users\/|\/home\/)[^\s]+/g,"[LOCAL_PATH]");}

  const configs={
    "har-sanitizer":{input:`<label for="input">HAR JSON</label><textarea id="input" class="advanced-input" placeholder="HARを貼り付けるかファイルを選択"></textarea><input id="file" class="advanced-field" type="file" accept=".har,.json">${buttons([["run","安全化する"],["sample","サンプル",true]])}`,output:`<pre id="result" class="advanced-output">安全化したHARが表示されます。</pre>${buttons([["save","JSONを保存"],["copy","コピー",true]])}`,run(){const {data,removed}=sanitizeHar(JSON.parse($("input").value));renderText(`削除・置換: ${removed}件\n\n${pretty(data)}`);this.value=pretty(data);}},
    "data-magic":{input:`<label for="input">判定するデータ</label><textarea id="input" class="advanced-input" placeholder="JSON、JWT、Base64、URLエンコード、Unix時刻など"></textarea>${buttons([["run","自動判定・変換"],["sample","サンプル",true]])}`,output:`<div id="result" class="result-list"><div class="result-item">候補をここに表示します。</div></div>`,run(){const r=dataMagic($("input").value);$("result").innerHTML=r.map(([n,v])=>`<div class="result-item"><strong>${esc(n)}</strong><pre>${esc(v)}</pre></div>`).join("");}},
    "curl-converter":{input:`<label for="input">cURLコマンド</label><textarea id="input" class="advanced-input" placeholder="curl -X POST ..."></textarea>${buttons([["run","コードへ変換"],["sample","サンプル",true]])}`,output:`<label for="format">出力形式</label><select id="format" class="advanced-field"><option>Fetch</option><option>Axios</option><option>Python</option><option>PowerShell</option></select><pre id="result" class="advanced-output">変換コードが表示されます。</pre>${buttons([["copy","コピー",true]])}`,run(){this.outputs=curlOutputs(parseCurl($("input").value));renderText(this.outputs[$("format").value]);}},
    "api-diff":{input:`<label for="old">変更前JSON</label><textarea id="old" class="advanced-input"></textarea><label for="new">変更後JSON</label><textarea id="new" class="advanced-input"></textarea>${buttons([["run","差分を検査"],["sample","サンプル",true]])}`,output:`<div id="result" class="result-list"><div class="result-item">破壊的変更と追加項目を分類します。</div></div>`,run(){const r=apiDiff(JSON.parse($("old").value),JSON.parse($("new").value));$("result").innerHTML=(r.length?r:[{level:"info",text:"構造上の差分はありません"}]).map(x=>`<div class="result-item ${x.level}">${esc(x.text)}</div>`).join("");}},
    "regex-safety":{input:`<label for="pattern">正規表現</label><input id="pattern" class="advanced-field" placeholder="例: (a+)+$"><div class="advanced-row"><div><label for="flags">フラグ</label><input id="flags" class="advanced-field" value="g"></div><div></div></div><label for="input">テスト文字列</label><textarea id="input" class="advanced-input"></textarea>${buttons([["run","安全性と一致を確認"],["sample","サンプル",true]])}`,output:`<div id="result" class="result-list"></div>`,run(){const p=$("pattern").value,w=regexAudit(p),flags=$("flags").value,re=new RegExp(p,flags.includes("g")?flags:`${flags}g`);const matches=[...$("input").value.matchAll(re)].slice(0,100);$("result").innerHTML=[...w.map(t=>({level:"danger",text:t})),{level:"info",text:`一致: ${matches.length}件`},...matches.slice(0,20).map(m=>({level:"info",text:`位置 ${m.index}: ${m[0]}`}))].map(x=>`<div class="result-item ${x.level}">${esc(x.text)}</div>`).join("");}},
    "csp-builder":{input:`<label for="input">現在のCSP（空欄なら安全な初期案を生成）</label><textarea id="input" class="advanced-input" placeholder="default-src 'self'; ..."></textarea><label for="domains">追加を許可するドメイン（空白区切り）</label><input id="domains" class="advanced-field" placeholder="https://cdn.example.com">${buttons([["run","CSPを作成・診断"],["sample","サンプル",true]])}`,output:`<pre id="result" class="advanced-output"></pre><div id="warnings" class="result-list"></div>${buttons([["copy","CSPをコピー",true]])}`,run(){const domains=$("domains").value.trim();const value=$("input").value.trim()||`default-src 'self'; script-src 'self'${domains?` ${domains}`:""}; style-src 'self'; img-src 'self' data:; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'; upgrade-insecure-requests`;this.value=value;renderText(value);const w=cspAudit(value);$("warnings").innerHTML=(w.length?w:["重大な注意候補はありません"]).map((t,i)=>`<div class="result-item ${w.length?"warn":""}">${esc(t)}</div>`).join("");}},
    "certificate-checker":{input:`<label for="host">ホスト名</label><input id="host" class="advanced-field" placeholder="example.com"><p class="advanced-note">ブラウザの制約により証明書本体には直接アクセスできないため、HTTPS接続可否と有効な接続先を確認します。</p>${buttons([["run","HTTPS接続を確認"],["sample","サンプル",true]])}`,output:`<div id="result" class="result-list"><div class="result-item">確認結果を表示します。</div></div>`,async run(){let host=$("host").value.trim().replace(/^https?:\/\//,"").split("/")[0];if(!host)throw Error("ホスト名を入力してください");$("result").innerHTML=`<div class="result-item">接続確認中…</div>`;try{await fetch(`https://${host}/`,{mode:"no-cors",cache:"no-store"});$("result").innerHTML=`<div class="result-item"><strong>HTTPS接続を開始できました</strong><br>対象: ${esc(host)}<br>詳細な発行者・期限はブラウザの鍵アイコンから確認してください。</div>`;}catch(e){$("result").innerHTML=`<div class="result-item danger">HTTPS接続を確認できませんでした。ホスト名、証明書、ネットワーク設定を確認してください。</div>`;}}},
    "cron-calendar":{input:`<label for="input">Cron式（分 時 日 月 曜日）</label><input id="input" class="advanced-field" value="0 9 * * 1-5">${buttons([["run","次回実行を計算"],["sample","サンプル",true]])}<p class="advanced-note">端末のタイムゾーン（日本設定なら日本時間）で計算します。</p>`,output:`<div id="result" class="result-list"></div>`,run(){const r=nextCron($("input").value);$("result").innerHTML=r.map((d,i)=>`<div class="result-item"><strong>${i+1}回目</strong> ${esc(d.toLocaleString("ja-JP",{dateStyle:"full",timeStyle:"short"}))}</div>`).join("");}},
    "actions-audit":{input:`<label for="input">GitHub Actions YAML</label><textarea id="input" class="advanced-input"></textarea>${buttons([["run","安全性を監査"],["sample","サンプル",true]])}`,output:`<div id="result" class="result-list"></div>`,run(){const r=actionsAudit($("input").value);$("result").innerHTML=(r.length?r:[{level:"info",text:"既知の危険パターンは見つかりませんでした"}]).map(x=>`<div class="result-item ${x.level}">${esc(x.text)}</div>`).join("");}},
    "error-pack":{input:`<label for="error">エラーログ</label><textarea id="error" class="advanced-input"></textarea><div class="advanced-row"><div><label for="env">環境</label><textarea id="env" class="advanced-input" placeholder="OS、ブラウザ、バージョン"></textarea></div><div><label for="steps">再現手順</label><textarea id="steps" class="advanced-input"></textarea></div></div><label><input id="mask" type="checkbox" checked> メール・トークン・ローカルパスをマスキング</label>${buttons([["run","共有パックを作成"],["sample","サンプル",true]])}`,output:`<pre id="result" class="advanced-output"></pre>${buttons([["copy","Markdownをコピー"],["save","保存",true]])}`,run(){let log=$("error").value;if($("mask").checked)log=redact(log);const lines=log.split("\n").filter((x,i,a)=>i===0||x!==a[i-1]);this.value=`## 発生した問題\n\n\`\`\`text\n${lines.join("\n")}\n\`\`\`\n\n## 環境\n\n${$("env").value||"未記入"}\n\n## 再現手順\n\n${$("steps").value||"未記入"}\n\n## 期待する結果\n\n未記入`;renderText(this.value);}}
  };

  const samples={"har-sanitizer":`{"log":{"entries":[{"request":{"url":"https://api.example.com?token=abc","headers":[{"name":"Authorization","value":"Bearer secret"}],"cookies":[{"name":"session","value":"xyz"}]}}]}}`,"data-magic":"eyJ1c2VyIjoidGFybzEifQ==","curl-converter":`curl -X POST "https://api.example.com/users" -H "Content-Type: application/json" -d '{"name":"Taro"}'`,"api-diff":null,"regex-safety":null,"csp-builder":`default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.example.com; img-src * data:`,"certificate-checker":"example.com","cron-calendar":"*/15 9-17 * * 1-5","actions-audit":`name: CI\non: pull_request_target\njobs:\n  test:\n    runs-on: ubuntu-latest\n    permissions: write-all\n    steps:\n      - uses: actions/checkout@main\n      - run: curl https://example.com/install.sh | sh`,"error-pack":null};
  const key=document.body.dataset.tool, cfg=configs[key], root=$("advancedApp"); if(!cfg||!root)return;
  root.innerHTML=panel(cfg.input,cfg.output,key==="certificate-checker"?"入力したホストへHTTPS接続確認を行います。結果は必ず目視でも確認してください。":"入力内容は保存・送信せず、このブラウザ内で処理します。結果は必ず目視でも確認してください。");
  const run=async()=>{try{await cfg.run();}catch(e){if($("result"))$("result").innerHTML=`<div class="result-item danger">${esc(e.message)}</div>`;}};
  $("run")?.addEventListener("click",run); $("copy")?.addEventListener("click",()=>copy(cfg.value||$("result").textContent)); $("save")?.addEventListener("click",()=>download(key==="har-sanitizer"?"sanitized.har":"error-report.md",cfg.value||$("result").textContent,key==="har-sanitizer"?"application/json":"text/markdown"));
  $("format")?.addEventListener("change",()=>cfg.outputs&&renderText(cfg.outputs[$("format").value]));
  $("file")?.addEventListener("change",async e=>{$("input").value=await e.target.files[0].text();});
  $("sample")?.addEventListener("click",()=>{if(key==="api-diff"){$("old").value='{"id":1,"name":"A","profile":{"age":20}}';$("new").value='{"id":"1","displayName":"A"}';}else if(key==="regex-safety"){$("pattern").value="(a+)+$";$("input").value="aaaaaaaaaaaaaaaa!";}else if(key==="error-pack"){$("error").value="TypeError: Failed at C:\\Users\\taro\\app.js\napi_key=secret123\nuser@example.com";$("env").value="Windows / Chrome";$("steps").value="1. 保存ボタンを押す\n2. エラーが表示される";}else{const target=$("input")||$("host");target.value=samples[key]||"";}run();});
  if(key==="cron-calendar")run();
  if(typeof module!=="undefined")module.exports={sanitizeHar,dataMagic,parseCurl,apiDiff,regexAudit,cspAudit,nextCron,actionsAudit,redact};
})();
