document.addEventListener("DOMContentLoaded",()=>{
const $=id=>document.getElementById(id),canvas=$("wheel"),ctx=canvas.getContext("2d"),colors=["#7c3aed","#2563eb","#0891b2","#059669","#65a30d","#ca8a04","#ea580c","#dc2626","#db2777","#9333ea"];let angle=0,spinning=false,winnerIndex=-1,history=[],audio=null;
const style=document.createElement("style");style.textContent=".candidate-list{display:grid;gap:9px;margin-top:14px}.candidate-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px}.candidate-input{width:100%;padding:11px 12px;border:1px solid #cbd5e1;border-radius:9px;font:15px/1.5 inherit}.candidate-delete{padding:9px 13px;background:#fee2e2;color:#b91c1c}.candidate-add{width:100%;margin-top:11px;background:#eef2ff;color:#4338ca;font-weight:800}";document.head.append(style);
const old=$("items"),candidateList=document.createElement("div"),add=document.createElement("button");candidateList.id="candidateList";candidateList.className="candidate-list";add.id="addCandidate";add.type="button";add.className="candidate-add";add.textContent="＋ 候補を追加";old.insertAdjacentElement("beforebegin",candidateList);old.insertAdjacentElement("beforebegin",add);old.remove();
function values(){return [...candidateList.querySelectorAll(".candidate-input")].map(x=>x.value.trim()).filter(Boolean)}
function addRow(value=""){const row=document.createElement("div");row.className="candidate-row";row.innerHTML='<input class="candidate-input" type="text" aria-label="ルーレット候補"><button class="candidate-delete" type="button" aria-label="候補を削除">削除</button>';row.querySelector("input").value=value;row.querySelector("input").addEventListener("input",()=>{if(!spinning)draw()});row.querySelector("button").onclick=()=>{if(candidateList.children.length<=2)return;row.remove();draw()};candidateList.append(row)}
["りんご","みかん","ぶどう","バナナ","いちご","メロン"].forEach(addRow);add.onclick=()=>{addRow("");candidateList.lastElementChild.querySelector("input").focus();draw()};
function draw(){const items=values(),n=Math.max(items.length,1),arc=Math.PI*2/n,r=canvas.width/2;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.save();ctx.translate(r,r);ctx.rotate(angle);if(!items.length){ctx.beginPath();ctx.arc(0,0,r-12,0,Math.PI*2);ctx.fillStyle="#cbd5e1";ctx.fill()}items.forEach((item,i)=>{const a=i*arc-Math.PI/2;ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,r-12,a,a+arc);ctx.closePath();ctx.fillStyle=colors[i%colors.length];ctx.fill();ctx.strokeStyle="#fff";ctx.lineWidth=5;ctx.stroke();ctx.save();ctx.rotate(a+arc/2);ctx.textAlign="right";ctx.fillStyle="#fff";ctx.font=`800 ${Math.max(18,Math.min(34,260/n+14))}px sans-serif`;ctx.shadowColor="#0008";ctx.shadowBlur=3;ctx.fillText(item.length>16?item.slice(0,15)+"…":item,r-42,10);ctx.restore()});ctx.beginPath();ctx.arc(0,0,72,0,Math.PI*2);ctx.fillStyle="#fff";ctx.fill();ctx.strokeStyle="#e2e8f0";ctx.lineWidth=5;ctx.stroke();ctx.restore();$("itemCount").textContent=`${items.length}項目`}
function random(){try{return window.crypto.getRandomValues(new Uint32Array(1))[0]/4294967296}catch(e){return Math.random()}}
function beep(freq=650,d=.035){if(!$("sound").checked)return;try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;audio=audio||new AC();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch(e){}}
function confetti(){for(let i=0;i<60;i++){const e=document.createElement("i");e.className="confetti";e.style.left=Math.random()*100+"vw";e.style.top="-20px";e.style.background=colors[i%colors.length];e.style.setProperty("--x",(Math.random()*300-150)+"px");e.style.animationDelay=Math.random()*.4+"s";document.body.append(e);setTimeout(()=>e.remove(),2500)}}
function renderHistory(){$("history").innerHTML=history.length?history.map((x,i)=>`<div><strong>${history.length-i}回目</strong> ${x.replace(/</g,"&lt;")}</div>`).join(""):"<div>まだ抽選されていません。</div>"}
$("spin").addEventListener("click",()=>{const items=values();if(spinning)return;if(items.length<2){$("winnerName").textContent="候補を2つ以上入力してください";$("winner").classList.add("show");return}spinning=true;$("spin").disabled=true;$("winner").classList.remove("show");const rand=random(),winner=Math.floor(rand*items.length),arc=Math.PI*2/items.length,current=((angle%(Math.PI*2))+Math.PI*2)%(Math.PI*2),target=(Math.PI*2-winner*arc-arc/2)%(Math.PI*2),delta=((target-current+Math.PI*2)%(Math.PI*2))+Math.PI*2*(6+Math.floor(rand*3)),start=performance.now(),duration=4800;let last=-1;function frame(now){const t=Math.min(1,(now-start)/duration),ease=1-Math.pow(1-t,4);angle=current+delta*ease;const tick=Math.floor(angle/arc);if(tick!==last){beep();last=tick}draw();if(t<1)requestAnimationFrame(frame);else{spinning=false;winnerIndex=winner;$("spin").disabled=false;$("winnerName").textContent=items[winner];$("winner").classList.add("show");history.unshift(items[winner]);renderHistory();beep(900,.18);confetti()}}requestAnimationFrame(frame)});
$("removeWinner").onclick=()=>{const rows=[...candidateList.children].filter(r=>r.querySelector("input").value.trim());if(winnerIndex<0||!rows[winnerIndex])return;rows[winnerIndex].remove();winnerIndex=-1;$("winner").classList.remove("show");draw()};$("shuffle").onclick=()=>{const a=values();for(let i=a.length-1;i;i--){const j=Math.floor(random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}candidateList.innerHTML="";a.forEach(addRow);draw()};$("reset").onclick=()=>{history=[];renderHistory()};draw();
});
