function initSiteSearch(){
const header=document.querySelector("header");if(!header||document.getElementById("siteSearch"))return;const toolPage=location.pathname.includes("/tools/");
const data=[["counter","📝","文字数カウント","文章 文字数 空白除外 行数 原稿"],["calculator","🧮","電卓","四則演算 計算 数学"],["timer","⏱️","タイマー・ストップウォッチ","時間 カウントダウン 計測 アラーム"],["test-data-generator","🗄️","テーブルINSERT生成","SQL テストデータ INSERT データベース"],["table-generator","🧱","CREATE TABLE生成","SQL DDL カラム データ型"],["image-editor","🖼️","画像編集","写真 文字入れ 合成 切り抜き 背景削除 圧縮 リサイズ"],["video-editor","🎬","動画編集","カット 字幕 速度 回転 色調 音量 圧縮"],["privacy-checker","🔒","公開前プライバシー検査","個人情報 APIキー パスワード マスキング"],["qr-reader","📷","QRコード読み取り","画像 カメラ スキャン 二次元コード"],["qr-generator","🔳","QRコード生成","URL 文章 二次元コード 作成 PNG"],["barcode-generator","🏷️","バーコード生成","商品番号 CODE128 EAN JAN SVG"],["password-generator","🔑","パスワード生成","安全 ランダム 文字列 セキュリティ"],["roulette","🎡","ルーレット","抽選 回転 アニメーション 当選 順番決め"],["random-picker","🎯","抽選・ランダム選択","候補 くじ 公平 シャッフル"],["unit-converter","📐","単位変換","長さ 重さ 面積 データ容量 km kg 坪"],["color-converter","🎨","カラーコード変換","HEX RGB HSL 色 ピッカー"],["date-calculator","🗓️","日付・年齢・元号計算","平成 令和 和暦 年度 生年月日"],["bmi-calculator","⚖️","BMI・適正体重計算","身長 体重 肥満 基礎代謝 カロリー"],["loan-calculator","🏦","ローン返済計算","住宅 借入 金利 毎月返済 利息"],["percentage-calculator","％","パーセント計算","割合 増減率 割引 百分率"],["text-diff","🆚","文章比較・差分チェック","テキスト 変更 追加 削除 比較"],["json-formatter","🧩","JSON整形・検証","フォーマット 構文エラー 圧縮 開発"],["csv-json-converter","🔄","CSV・JSON相互変換","表 データ 変換 カンマ 開発"],["hash-generator","#️⃣","ハッシュ生成","SHA256 SHA512 チェックサム ファイル"],["data-magic","✨","データ自動判定・変換","Base64 JWT URL 16進数 Unix時刻"],["api-diff","🔍","APIレスポンス差分","JSON 破壊的変更 型 比較"],["curl-converter","🔁","cURL変換","Fetch Axios Python PowerShell API"],["regex-safety","🧪","正規表現安全性チェック","Regex ReDoS 一致 パターン"],["csp-builder","🛡️","CSP作成・診断","Content Security Policy セキュリティ"],["certificate-checker","📜","HTTPS証明書接続チェック","SSL TLS ドメイン セキュリティ"],["actions-audit","⚙️","GitHub Actions安全監査","YAML CI CD 権限"],["cron-calendar","📅","Cron実行カレンダー","スケジュール 次回実行 日時"],["error-pack","📦","エラー共有パック","ログ 再現手順 GitHub Issue Markdown"],["har-sanitizer","🧹","HAR安全共有","通信記録 Cookie Authorization 認証情報"],["pdf-tools","📄","PDF総合ツール","結合 分割 圧縮 回転 ページ削除 透かし"]];
document.querySelectorAll(".tool-card").forEach(card=>{const link=card.getAttribute("href")||"",title=card.querySelector("h2")?.textContent.trim(),description=card.querySelector("p")?.textContent.trim()||"";if(!title||!link)return;const slug=(link.split("/").pop()||"").replace(/\.html$/,"");if(slug&&!data.some(x=>x[0]===slug))data.push([slug,"🔧",title,description]);});
const pageHeading=document.querySelector("h1")?.textContent.replace(/^[^\p{L}\p{N}]+/u,"").trim();if(toolPage&&pageHeading){const slug=(location.pathname.split("/").pop()||"").replace(/\.html$/,"");const meta=document.querySelector('meta[name="description"]')?.content||"";if(slug&&!data.some(x=>x[0]===slug))data.push([slug,"🔧",pageHeading,meta]);}
const box=document.createElement("div");box.className="site-search";box.innerHTML='<label class="site-search-label"><span>🔎</span><input id="siteSearch" type="search" placeholder="機能や目的を検索" autocomplete="off" aria-label="機能検索"></label><div id="siteSearchResults" class="site-search-results"></div>';header.append(box);const input=document.getElementById("siteSearch"),results=document.getElementById("siteSearchResults"),norm=s=>s.normalize("NFKC").toLowerCase().replace(/[\s・_\-／/]/g,"");
function dist(a,b){const d=Array.from({length:a.length+1},(_,i)=>[i]);for(let j=0;j<=b.length;j++)d[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)d[i][j]=Math.min(d[i-1][j]+1,d[i][j-1]+1,d[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return d[a.length][b.length]}function sub(q,s){let i=0;for(const c of s)if(c===q[i])i++;return i===q.length}
function find(q){const n=norm(q);if(!n)return[];return data.map(x=>{const name=norm(x[2]),desc=norm(x[3]);let score=name.includes(n)?120:desc.includes(n)?90:0;if(!score&&n.length>=2&&(sub(n,name)||sub(n,desc)))score=55;if(!score&&n.length>=3&&(x[2]+" "+x[3]).split(/\\s+/).some(w=>dist(n,norm(w))<=Math.min(2,Math.floor(n.length/3))))score=40;return{x,score}}).filter(v=>v.score).sort((a,b)=>b.score-a.score).slice(0,12)}
function render(){const f=find(input.value);if(!input.value.trim()){results.classList.remove("open");return}results.innerHTML=f.length?f.map(({x})=>`<a href="${toolPage?x[0]+".html":"tools/"+x[0]+".html"}"><span class="search-result-icon">${x[1]}</span><span><strong>${x[2]}</strong><small>${x[3]}</small></span></a>`).join(""):'<div class="search-empty">該当する機能がありません</div>';results.classList.add("open")}input.addEventListener("input",render);input.addEventListener("focus",render);input.addEventListener("keydown",e=>{const a=[...results.querySelectorAll("a")];if(e.key==="ArrowDown"&&a.length){e.preventDefault();a[0].focus()}if(e.key==="Escape")results.classList.remove("open")});document.addEventListener("click",e=>{if(!box.contains(e.target))results.classList.remove("open")});
}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",initSiteSearch);else initSiteSearch();
