document.addEventListener("DOMContentLoaded",()=>{
const $=id=>document.getElementById(id),video=$("video"),stage=$("stage"),overlay=$("overlay"),seek=$("seek");let url="",rotation=0,flipX=1,flipY=1,exporting=false,audioCtx=null,audioSource=null;
const fmt=(s,t=false)=>{if(!Number.isFinite(s))return"00:00";const m=Math.floor(s/60),v=t?(s%60).toFixed(1):String(Math.floor(s%60)).padStart(2,"0");return`${String(m).padStart(2,"0")}:${String(v).padStart(t?4:2,"0")}`};
const filter=()=>`brightness(${$("brightness").value}%) contrast(${$("contrast").value}%) saturate(${$("saturation").value}%) blur(${$("blur").value}px)`;
const transform=()=>`rotate(${rotation}deg) scale(${flipX},${flipY})`;
function dims(){let w=video.videoWidth||1920,h=video.videoHeight||1080;const ratio=$("aspectRatio").value;if(ratio!=="source"){const [a,b]=ratio.split(":").map(Number),target=a/b;if(w/h>target)w=Math.round(h*target);else h=Math.round(w/target);}return{w,h};}
function fadeAlpha(){const start=Number($("trimStart").value),end=Number($("trimEnd").value),t=video.currentTime,fi=Number($("fadeIn").value),fo=Number($("fadeOut").value);return Math.min(1,fi?Math.max(0,(t-start)/fi):1,fo?Math.max(0,(end-t)/fo):1);}
function update(){stage.style.setProperty("--filter",filter());stage.style.setProperty("--transform",transform());overlay.textContent=$("overlayText").value;overlay.style.fontSize=`${$("fontSize").value}px`;overlay.style.top=`${$("textY").value}%`;overlay.style.setProperty("--text-color",$("textColor").value);video.playbackRate=Number($("speed").value);video.volume=Math.min(1,Number($("volume").value)/100);video.muted=$("mute").checked;["brightness","contrast","saturation"].forEach(id=>$(id+"Value").textContent=$(id).value+"%");$("blurValue").textContent=$("blur").value+"px";$("fontSizeValue").textContent=$("fontSize").value+"px";$("textYValue").textContent=$("textY").value+"%";$("volumeValue").textContent=$("volume").value+"%";["fadeIn","fadeOut","audioFadeIn","audioFadeOut"].forEach(id=>$(id+"Value").textContent=Number($(id).value).toFixed(1)+"秒");summary();}
function summary(){const s=Number($("trimStart").value),e=Number($("trimEnd").value);$("startValue").textContent=fmt(s,true);$("endValue").textContent=fmt(e,true);$("outputDuration").textContent=video.duration?fmt(Math.max(0,e-s)/Number($("speed").value)):"--";const d=dims();if(video.duration)$("resolution").textContent=`${d.w} × ${d.h}`;}
function toggle(){if(!video.src)return;video.paused?video.play():video.pause();}
$("videoFile").onchange=e=>{const f=e.target.files[0];if(!f)return;if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(f);video.src=url;$("status").textContent=`${f.name} を読み込み中…`;};
video.onloadedmetadata=()=>{stage.classList.add("ready");$("trimStart").max=$("trimEnd").max=video.duration;$("trimStart").value=0;$("trimEnd").value=video.duration;$("sourceDuration").textContent=fmt(video.duration);$("exportButton").disabled=false;$("status").textContent="編集できます。設定はプレビューと書き出しへ反映されます。";update();};
video.ontimeupdate=()=>{if(!exporting&&video.currentTime>Number($("trimEnd").value)){video.pause();video.currentTime=Number($("trimStart").value);}seek.value=video.duration?video.currentTime/video.duration*1000:0;$("time").textContent=`${fmt(video.currentTime)} / ${fmt(video.duration)}`;$("playButton").textContent=video.paused?"▶":"❚❚";video.style.opacity=fadeAlpha();};video.onplay=()=>$("playButton").textContent="❚❚";video.onpause=()=>$("playButton").textContent="▶";$("playButton").onclick=toggle;seek.oninput=()=>{if(video.duration)video.currentTime=seek.value/1000*video.duration;};
document.querySelectorAll(".ve-tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".ve-tab,.ve-pane").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.pane).classList.add("active");});
["overlayText","fontSize","textColor","textY","speed","brightness","contrast","saturation","blur","volume","mute","aspectRatio","fitMode","backgroundColor","fadeIn","fadeOut","audioFadeIn","audioFadeOut"].forEach(id=>$(id).addEventListener("input",update));
["trimStart","trimEnd"].forEach(id=>$(id).oninput=()=>{if(Number($("trimStart").value)>=Number($("trimEnd").value)){if(id==="trimStart")$("trimEnd").value=Math.min(video.duration,Number($(id).value)+.1);else $("trimStart").value=Math.max(0,Number($(id).value)-.1);}video.currentTime=Number($(id).value);summary();});
$("setStart").onclick=()=>{$("trimStart").value=Math.min(video.currentTime,Number($("trimEnd").value)-.1);summary();};$("setEnd").onclick=()=>{$("trimEnd").value=Math.max(video.currentTime,Number($("trimStart").value)+.1);summary();};$("resetTrim").onclick=()=>{$("trimStart").value=0;$("trimEnd").value=video.duration;summary();};
document.querySelectorAll(".transform").forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==="left")rotation-=90;if(a==="right")rotation+=90;if(a==="flipX")flipX*=-1;if(a==="flipY")flipY*=-1;if(a==="reset"){rotation=0;flipX=flipY=1;}update();});
$("resetColor").onclick=()=>{$("brightness").value=$("contrast").value=$("saturation").value=100;$("blur").value=0;update();};
const presets={natural:[105,105,110,0],cinema:[85,125,80,0],vivid:[108,115,145,0],mono:[100,120,0,0],soft:[112,90,85,1],night:[70,135,90,0]};const presetBox=document.createElement("div");presetBox.className="ve-preset";presetBox.innerHTML=Object.entries({natural:"ナチュラル",cinema:"シネマ",vivid:"鮮やか",mono:"モノクロ",soft:"ソフト",night:"夜景"}).map(([k,v])=>`<button type="button" data-preset="${k}">${v}</button>`).join("");$("color").insertBefore(presetBox,$("color").children[1]);presetBox.querySelectorAll("button").forEach(b=>b.onclick=()=>{const p=presets[b.dataset.preset];[$("brightness").value,$("contrast").value,$("saturation").value,$("blur").value]=p;presetBox.querySelectorAll("button").forEach(x=>x.classList.toggle("active",x===b));update();});
const qualityWrap=document.createElement("div");qualityWrap.className="ve-control";qualityWrap.innerHTML='<label for="quality">書き出し画質</label><select id="quality"><option value="4">標準（容量小）</option><option value="7" selected>高画質</option><option value="11">最高画質（容量大）</option></select>';$("exportButton").before(qualityWrap);
function canvasSize(){const d=dims(),q=Math.abs(rotation/90)%2===1;return{w:q?d.h:d.w,h:q?d.w:d.h};}
function draw(ctx,c){ctx.save();ctx.fillStyle=$("backgroundColor").value;ctx.fillRect(0,0,c.width,c.height);ctx.globalAlpha=fadeAlpha();ctx.filter=filter();ctx.translate(c.width/2,c.height/2);ctx.rotate(rotation*Math.PI/180);ctx.scale(flipX,flipY);const vw=video.videoWidth,vh=video.videoHeight,cover=$("fitMode").value==="cover",scale=cover?Math.max(c.width/vw,c.height/vh):Math.min(c.width/vw,c.height/vh),dw=vw*scale,dh=vh*scale;ctx.drawImage(video,-dw/2,-dh/2,dw,dh);ctx.restore();const text=$("overlayText").value.trim();if(text){const size=Math.max(18,Number($("fontSize").value)*c.width/Math.max(video.clientWidth,640));ctx.font=`800 ${size}px sans-serif`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.lineWidth=Math.max(3,size*.12);ctx.strokeStyle="#000d";ctx.fillStyle=$("textColor").value;const y=c.height*Number($("textY").value)/100;ctx.strokeText(text,c.width/2,y,c.width*.9);ctx.fillText(text,c.width/2,y,c.width*.9);}}
$("snapshotButton").onclick=()=>{if(!video.duration)return;const d=canvasSize(),c=document.createElement("canvas");c.width=d.w;c.height=d.h;draw(c.getContext("2d"),c);c.toBlob(blob=>{const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`video-frame-${Date.now()}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);},"image/png");};
document.addEventListener("keydown",e=>{if(["INPUT","TEXTAREA","SELECT"].includes(e.target.tagName))return;if(e.code==="Space"){e.preventDefault();toggle();}if(e.key==="ArrowLeft")video.currentTime=Math.max(0,video.currentTime-1);if(e.key==="ArrowRight")video.currentTime=Math.min(video.duration,video.currentTime+1);if(e.key.toLowerCase()==="i")$("setStart").click();if(e.key.toLowerCase()==="o")$("setEnd").click();});
$("exportButton").onclick=async()=>{if(exporting||!video.duration)return;if(!window.MediaRecorder||!HTMLCanvasElement.prototype.captureStream){$("status").textContent="ChromeまたはEdgeの新しいバージョンをお使いください。";return;}exporting=true;$("exportButton").disabled=true;const progress=$("exportProgress"),d=canvasSize(),c=document.createElement("canvas");c.width=d.w;c.height=d.h;const ctx=c.getContext("2d"),stream=c.captureStream(30);progress.classList.add("show");progress.value=0;let gain=null;try{if(!$("mute").checked){audioCtx=audioCtx||new AudioContext();audioSource=audioSource||audioCtx.createMediaElementSource(video);gain=audioCtx.createGain();const dest=audioCtx.createMediaStreamDestination();audioSource.connect(gain);gain.connect(dest);dest.stream.getAudioTracks().forEach(t=>stream.addTrack(t));}const mime=MediaRecorder.isTypeSupported("video/webm;codecs=vp9,opus")?"video/webm;codecs=vp9,opus":"video/webm",rate=Math.min(24000000,Math.max(2500000,c.width*c.height*Number($("quality").value)));const rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:rate}),chunks=[];rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};const done=new Promise(r=>rec.onstop=r),start=Number($("trimStart").value),end=Number($("trimEnd").value);video.pause();video.currentTime=start;await new Promise(r=>video.addEventListener("seeked",r,{once:true}));video.playbackRate=Number($("speed").value);rec.start(1000);await video.play();$("status").textContent="動画を書き出しています。ページを閉じないでください。";await new Promise(resolve=>{const loop=()=>{draw(ctx,c);const elapsed=video.currentTime-start,remain=end-video.currentTime,afi=Number($("audioFadeIn").value),afo=Number($("audioFadeOut").value);if(gain)gain.gain.value=Number($("volume").value)/100*Math.min(1,afi?elapsed/afi:1,afo?remain/afo:1);progress.value=Math.min(100,elapsed/(end-start)*100);if(video.currentTime>=end||video.ended){video.pause();resolve();}else requestAnimationFrame(loop);};loop();});rec.stop();await done;const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(chunks,{type:mime}));a.download=`edited-video-${Date.now()}.webm`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);$("status").textContent="書き出しが完了しました。";}catch(e){$("status").textContent=`書き出しに失敗しました: ${e.message}`;}finally{if(gain){audioSource.disconnect(gain);gain.disconnect();}exporting=false;$("exportButton").disabled=false;progress.classList.remove("show");}};
});
